export const BOOK_CATEGORIES = [
  'Produtividade',
  'Desenvolvimento Pessoal',
  'Hábitos',
  'Carreira',
  'Psicologia',
  'Filosofia',
  'Comportamento Humano',
  'Neurociência',
  'Ficção',
  'Fantasia',
  'Distopia',
  'Ficção Científica',
  'Aventura',
  'Romance',
  'Drama',
  'Mistério',
  'Suspense',
  'Thriller',
  'Crime',
  'Negócios',
  'Empreendedorismo',
  'Marketing',
  'Finanças',
  'Investimentos',
  'Tecnologia',
  'Programação',
  'Inteligência Artificial',
  'Ciência de Dados',
  'História',
  'Biografia',
  'Autoajuda',
  'Educação',
  'Ciência',
  'Arte',
  'Literatura Clássica',
] as const;
