export const BOOK_CATEGORIES = [
  'Arte',
  'Autoajuda',
  'Aventura',
  'Biografia',
  'Carreira',
  'Ciência',
  'Ciência de Dados',
  'Comportamento Humano',
  'Crime',
  'Desenvolvimento Pessoal',
  'Distopia',
  'Drama',
  'Educação',
  'Empreendedorismo',
  'Fantasia',
  'Ficção',
  'Ficção Científica',
  'Filosofia',
  'Finanças',
  'Hábitos',
  'História',
  'Inteligência Artificial',
  'Investimentos',
  'Literatura Clássica',
  'Marketing',
  'Mistério',
  'Negócios',
  'Neurociência',
  'Produtividade',
  'Programação',
  'Psicologia',
  'Romance',
  'Suspense',
  'Tecnologia',
  'Thriller',
] as const;
